# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_list', models.CharField(max_length=1000)),
                ('env', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100, null=True)),
                ('requested_by', models.CharField(max_length=100, null=True)),
                ('request_date', models.DateField(auto_now_add=True, null=True)),
                ('approved_by', models.CharField(max_length=100, null=True)),
                ('approved_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'access_requests',
                'permissions': (('can_raise_request', 'Can Raise Access Request'), ('can_approve_request', 'Can Approve Access Request'), ('can_reject_request', 'Can Reject Access Request')),
            },
        ),
    ]
